[tool.poetry]
name = "oim-stats-server"
version = "0.1.0"
description = ""
authors = ["Russ Garrett <russ@garrett.co.uk>"]

[tool.poetry.dependencies]
python = ">=3.7"
starlette = "^0.23.1"
databases = "^0.7.0"
asyncpg = "^0.27.0"
aiofiles = "^0.5.0"
jinja2 = "^3.1.2"
uvicorn = "^0.20.0"
asgi-sitemaps = "^0.3.2"
aiohttp = "^3.8.3"
more-itertools = "^8.6.0"
async_lru = "^1.0.2"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
mypy = "^0.991"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
