name: Build tile server containers

on:
  push:
    branches: 
      - main
    paths:
      - 'tegola/**'
      - '.github/workflows/tileserver.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push tileserver image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./tegola
          file: ./tegola/Dockerfile
          push: true
          tags: |
            ghcr.io/openinframap/tileserver:${{ github.sha }}-${{ github.run_number }}
            ghcr.io/openinframap/tileserver:latest
      - name: Build and push tileserver-expiry image
        id: docker_build_expiry
        uses: docker/build-push-action@v4
        with:
          context: ./tegola
          file: ./tegola/Dockerfile.expiry
          push: true
          tags: |
            ghcr.io/openinframap/tileserver-expiry:${{ github.sha }}-${{ github.run_number }}
            ghcr.io/openinframap/tileserver-expiry:latest