name: Build web router container

on:
  push:
    branches:
      - main
    paths:
      - 'web-router/**'
      - '.github/workflows/web-router.yml'

jobs:
  login:
    env:
      IMAGE: ghcr.io/openinframap/openinframap-web-router
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
            context: ./web-router
            file: ./web-router/Dockerfile
            push: true
            tags: |
                ${{ env.IMAGE }}:${{ github.sha }}-${{ github.run_number }}
