name: Build web backend

on:
  push:
    branches: 
      - main
    paths:
      - 'web-backend/**'
      - '.github/workflows/web-backend.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: '0.6.2'
      - name: Install dependencies
        run: |
          cd web-backend
          uv python install
          uv sync
      - name: Run tests
        run: |
          cd web-backend
          uv run ruff check
          uv run mypy .
          uv run pytest
      
  build:
    needs: test
    if: github.ref == 'refs/heads/main'
    env:
      IMAGE: ghcr.io/openinframap/web-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./web-backend
          file: ./web-backend/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ github.sha }}-${{ github.run_number }}
