name: Build web container

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - '.github/workflows/web.yml'

jobs:
  login:
    env:
      IMAGE: ghcr.io/openinframap/web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./web
          file: ./web/Dockerfile.prod
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ github.sha }}-${{ github.run_number }}
